version: '0.1'
services:
  # Define a service "server" that builds from the Dockerfile in the current directory.
  server:
    # Name of the container that will be created from the GraphQL service.
    container_name: leftover-label-printer-server
    platform: linux/amd64
    # devices:
      # share dev folder so usb printer can be used
      # - /dev/usb:/dev/usb
    build:
      # The context is the directory containing the Dockerfile.
      context: .
      # The name of the Dockerfile to be used.
      dockerfile: Dockerfile
    # Expose and map port 4000 on the host to port 4000 on the service.
    # This enables accessing the service at localhost:4000.
    ports:
      - 4000:4000
    # Use volumes to persist data and optimize the performance.
    volumes:
      # Mount the current directory from the host to '/app' in the container.
      - .:/app
